apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "app.fullname" . }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "app.name" . }}

    spec:
      imagePullSecrets:
        - name: harbor-registry-secret
      containers:
      - name: app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080

        resources:
          {{- toYaml .Values.resources | nindent 10 }}