apiVersion: v1
kind: Service

metadata:
  name: {{ include "app.fullname" . }}

spec:
  selector:
    app: {{ include "app.name" . }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8080

  type: {{ .Values.service.type | default "ClusterIP" }}